// ============================================================
// Gallery Type Definitions — FNSG Photo Gallery System
// Cloudinary-powered image delivery + optimization
// ============================================================

export type GalleryCategory =
    | 'team-events'
    | 'community'
    | 'workplace'
    | 'celebrations'
    | 'training'
    | 'leadership';

export interface GalleryImage {
    /** Unique identifier for the image */
    id: string;
    /** Cloudinary public_id (e.g., "fnsg-gallery/holiday-celebration-2025/team-dinner") */
    publicId: string;
    /** Full Cloudinary delivery URL (auto-generated by cloudinaryUrl helper) */
    src: string;
    /** SEO-optimized alt text describing the image content */
    alt: string;
    /** Original image width in pixels */
    width: number;
    /** Original image height in pixels */
    height: number;
    /** Category for filtering */
    category: GalleryCategory;
    /** Event or occasion name */
    event: string;
    /** Date of the photo (YYYY-MM-DD) */
    date: string;
    /** Short caption displayed below the image */
    caption?: string;
    /** Whether this image appears in compact/featured mode */
    featured?: boolean;
    /** Display priority within its category (lower = first) */
    order?: number;
    /** Aspect ratio hint for masonry layout */
    aspect?: 'landscape' | 'portrait' | 'square';
    /** Cloudinary format override (default: auto) */
    format?: string;
}

export interface GalleryEvent {
    /** Unique slug for the event (kebab-case) */
    slug: string;
    /** Human-readable event name */
    name: string;
    /** Event date (YYYY-MM-DD) */
    date: string;
    /** Short description of the event */
    description: string;
    /** Category */
    category: GalleryCategory;
    /** Location where the event took place */
    location?: string;
    /** All images belonging to this event */
    images: GalleryImage[];
}

export interface GalleryFilterOption {
    value: GalleryCategory | 'all';
    label: string;
    count: number;
}

export interface PhotoGalleryProps {
    /** Display mode: "compact" for embedded, "full" for dedicated page */
    variant: 'compact' | 'full';
    /** Maximum images to show in compact mode (default: 6) */
    compactLimit?: number;
    /** Filter to a specific category */
    category?: GalleryCategory;
    /** Filter to a specific event slug */
    eventSlug?: string;
    /** Show category filter tabs (only in full mode) */
    showFilters?: boolean;
    /** Link to full gallery page (shown in compact mode) */
    galleryLink?: string;
    /** Custom heading text */
    heading?: string;
    /** Custom subheading text */
    subheading?: string;
}

/** Cloudinary transformation options for gallery images */
export interface CloudinaryTransform {
    width?: number;
    height?: number;
    crop?: 'fill' | 'fit' | 'limit' | 'thumb' | 'scale';
    gravity?: 'auto' | 'face' | 'faces' | 'center';
    quality?: 'auto' | 'auto:best' | 'auto:good' | 'auto:eco' | number;
    format?: 'auto' | 'webp' | 'avif' | 'jpg' | 'png';
    effect?: string;
    dpr?: 'auto' | number;
}
